### ISSUE TITLE
About limitation of GITHUB_TOKEN

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#9] opened 2019-09-02 05:58 UTC
GitHub Actions v2 is still beta and deploying to GitHub Pages with `GITHUB_TOKEN` has some problems. Until it is fixed, I provide `ACTIONS_DEPLOY_KEY` to deploy with ssh from `peaceiris/actions-gh-pages@v2.0.0`

**Comment by hakusaro** [comment] 2019-09-05 06:11
Does this cause the `fatal: could not read Username for 'https://github.com': No such device or address` error?

**Comment by peaceiris** [comment] 2019-09-05 06:16
No, your case seems to be new. Please create a new issue and tell me more details.

**Comment by thefringeninja** [comment] 2019-09-05 12:47
I ran into the same issue. The manual way to fix it is from settings, flip your branch to `master` and then back to `gh-pages`.

A better way to fix it is to create a personal access token and use that in secrets instead.

**Comment by peaceiris** [comment] 2019-09-05 12:52
Thanks @thefringeninja 
I will release `v2.0.0` soon. It supports `GITHUB_TOKEN` and `ACTIONS_DEPLOY_KEY`. `ACTIONS_DEPLOY_KEY` is for deploying with ssh.

> A better way to fix it is to create a personal access token and use that in secrets instead.

We will be able to set a personal access token as `ACTIONS_DEPLOY_KEY`

**Comment by peaceiris** [comment] 2019-09-05 14:25
`v2.0.0` is released.

**Comment by nicolas-van** [comment] 2019-09-06 14:38
@peaceiris : Do you know if there is a support ticket for this problem ?

**Comment by peaceiris** [comment] 2019-09-06 18:15
This problem is a known issue. I have faced the same issue on GitHub Actions v1. Thus, some people have reported this to GitHub support. As you see at the https://github.com/JamesIves/github-pages-deploy-action/issues/5, GitHub should already know this. If this issue is not fixed for a long time, we probably 
should report this in the [GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions) as well.

**Comment by peaceiris** [comment] 2019-09-10 04:57
I found the post on the GitHub Community Forum.

[Github action not triggering gh-pages upon push - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869)

Community Manager said:

> The `GITHUB_TOKEN` that is provided as a part of GitHub Actions doesn't have authorization to create any successive events, such as GitHub Pages builds. So while you can push to the `gh-pages` branch using the `GITHUB_TOKEN`, it won't spawn a GitHub Pages build. You'll need to create a personal access token and supply it to your GitHub Action as a secret.

**Comment by nicolas-van** [comment] 2019-09-10 07:22
Yes, it seems like that's not a bug but a normal behavior in the context of the security rule imposed in Github Actions which is "A workflow can not trigger another workflow".

I posted an answer to ask if they could re-consider this limitation in this precise use case due to the obvious usability issue it creates. I propose that we wait their answer and if it's negative we could just close this issue as "not a bug" and adapt the documentation of this project to explain it will never be possible to use `GITHUB_TOKEN`.

**Comment by peaceiris** [comment] 2019-09-10 07:34
Thank you @nicolas-van 

> Yes, it seems like that's not a bug but a normal behavior in the context of the security rule imposed in Github Actions which is "A workflow can not trigger another workflow".

I got it clearly. I will update the README following your suggestion.

**Comment by nicolas-van** [comment] 2019-09-11 11:28
Hmmm, according to the most recent answer of [this thread](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869) it might not be by design in the end. I'm gonna test what is proposed to see if it works when I have some time.

**Comment by peaceiris** [comment] 2019-09-11 13:07
Yes, I am also following that thread.

> Here's an example that should work:

```
# pushes using the user that kicked off the action. Requires `jq` in the builder
git config user.name $(jq .pusher.username $GITHUB_PAYLOAD)
git config user.email $(jq .pusher.email $GITHUB_PAYLOAD)

git add --all
git commit -m "Publish to gh-pages branch"
git remote add pages https://x-access-token:$GITHUB_TOKEN@github.com/:owner/:repo.git
git push pages gh-pages -f
```

This action already supports the above and I tested at [peaceiris/hugo-test-project]. I could push to `gh-pages` branch using `GITHUB_TOKEN` but GitHub Pages building did not start.

[peaceiris/hugo-test-project]: https://github.com/peaceiris/hugo-test-project/commit/47bd7cf05eb59aeaca809361792d6c5464e9afd3/checks

**Comment by peaceiris** [comment] 2019-10-01 05:19
I found it. The following step will work well.

```yaml
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.4.0/entrypoint.sh
        bash ./entrypoint.sh
```

**Comment by peaceiris** [comment] 2019-10-01 05:28
No, some repository faild.

**Comment by NGTmeaty** [comment] 2019-10-07 19:29
I have a private repo setup and GITHUB_TOKEN still isn't working. I see someone else above had the same issue as me: https://github.com/peaceiris/actions-gh-pages/issues/13 but he just moved to a deploy key. Do we know if there's a actual solution to that above?

**Comment by peaceiris** [comment] 2019-10-08 03:20
This problem is about permissions of the default token between GitHub Pages and GitHub Actions. GitHub team is investigating it and we are waiting for a good reply from them. Currently, there is no actual solution.

- [Github action not triggering gh-pages upon push - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869)

**Comment by NGTmeaty** [comment] 2019-10-08 03:29
I was using the PERSONAL_TOKEN env variable and passing in a GITHUB_TOKEN, oops :) Switching that to a GITHUB_TOKEN env variable with a GITHUB_TOKEN, everything worked perfectly :) Thanks!

**Comment by mikeal** [comment] 2019-11-14 00:26
I had a chat with someone at GitHub today about this very issue (calling Actions from other Actions) and found out that, while GitHub Actions won’t trigger push events for other actions, they do trigger repo events, so if you listen for a repo event instead of a the push event you avoid this issue.

**Comment by peaceiris** [comment] 2019-11-14 02:34
Thank you @mikeal 

Do you mean that the default `GITHUB_TOKEN` does not have permission for repo events on a public repository? I think the token has repo events access. Why cannot we trigger the GitHub Pages build event with the default `GITHUB_TOKEN` on a public repository? (On a private repository, we can do that.)

**Comment by shaunakv1** [comment] 2019-11-18 05:54
Hello, 

In my case I am added as a collaborator (full admin access) to an Organization. I am trying to setup a simple static site push to gh-pages. I have setup using `ACTIONS_DEPLOY_KEY`. The deploy succeeds but the site changes are not reflected. In-fact if I manually delete gh-pages branch and re-run the action, it succeeds again, but the site is never published. All the code seems okay in gh-pages.  What am I doing wrong?  here' s my action yaml


```yaml
name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v1

      - name: Build
        run: |
          rm -rf dist
          rsync -rv --exclude=.git --exclude=.github . dist

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist

```

**Comment by peaceiris** [comment] 2019-11-18 05:58
@shaunakv1 Please go to #52

**Comment by mikeal** [comment] 2019-11-20 18:32
@peaceiris I miss-interpreted the issue a little bit. This is going to be an issue unless github moves their *internal* event signal for gh-pages to this, there’s no much we can do on the outside 😰

**Comment by peaceiris** [comment] 2020-01-05 07:16
The deployment key option is still a current workaround better than a personal access token (PAT has too large scope). I hope that GitHub Pages build event can be triggered by GITHUB_TOKEN on a public repository. (GITHUB_TOKEN can trigger the event on a private repository.)

**Comment by peaceiris** [comment] 2020-02-05 08:22
v3 has been released. But we cannot use `GITHUB_TOKEN` on a public repository.

**Comment by peaceiris** [comment] 2020-02-15 03:59
I found a very interesting proposal at [revise adr to support ssh by ericsciple · Pull Request #156 · actions/checkout](https://github.com/actions/checkout/pull/156).

**Comment by peaceiris** [comment] 2020-02-15 04:24
Hi, all!

Now, I tested deployment with `github_token` on some repositories. It looks working well...

I do not know any official announcement of the GitHub starts to support running the GitHub Pages build event using `GITHUB_TOKEN` on public repositories...

**Comment by nicolas-van** [comment] 2020-02-17 14:26
I can also confirm it works. Demonstration on this repository: https://github.com/nicolas-van/hugotest

Hurray !

**Comment by dhimmel** [comment] 2020-02-17 22:14
Also having success with `secrets.DEPLOY_KEY` deploying to GitHub Pages on a public repo in https://github.com/manubot/rootstock/pull/310 (does not use this action). Thanks @peaceiris for monitoring this. Hopefully, the fix is permanent!

**Comment by peaceiris** [comment] 2020-02-18 15:21
Unfortunately, the build with `GITHUB_TOKEN` sometimes fails...

**Comment by nicolas-van** [comment] 2020-02-18 15:36
Didn't had a problem personally.

The only strange behavior I encountered was that, when I created [this repository](https://github.com/nicolas-van/parcel-github-pages-boilerplate) (which is a reusable boilerplate for Parcel I was hoping to create for a long time by the way), I had to kind of "confirm" to Github in the settings of the repository that I really wanted to deploy that web site from the `gh-pages` branch. 

Then I made 40+ commits that all triggered a publish without problem.

**Comment by peaceiris** [comment] 2020-02-18 16:02
@nicolas-van Thank you for telling me your log and the boilerplate looks very useful.

In my case, when I push two commits with shorter intervals, the first one fails.

<img width="1130" alt="Screen Shot 2020-02-19 at 0 59 26" src="https://user-images.githubusercontent.com/30958501/74753352-59f3e080-52b3-11ea-870b-bf47d083ce5b.png">

[Commits master branch · peaceiris/peaceiris.github.io](https://github.com/peaceiris/peaceiris.github.io/commits/master)

**Comment by peaceiris** [comment] 2020-02-18 16:15
From another point of view, that behavior also sounds good. When the second event starts in the middle of the first one, the first one may be canceled. It is my expectation.

**Comment by peaceiris** [comment] 2020-02-18 17:09
See https://github.com/peaceiris/actions-gh-pages/issues/104#issue-566391138

> I am attempting to use `secrets.GITHUB_TOKEN` on a public repository. The one commit that did get generated and pushed to `gh-pages`, does not seem to have triggered a GitHub Pages build, despite reports this is now working at #9 (comment).

**Comment by dhimmel** [comment] 2020-02-18 17:31
I addition to the quote above. I've also experienced inconsistent triggering of GitHub Pages build at https://github.com/dhimmel/rootstock-branchless-setup/commits/gh-pages:

> ![image](https://user-images.githubusercontent.com/1117703/74761563-3e082480-524a-11ea-8473-9d79d9c40e07.png)

See how the first commit did not trigger a build. I switched GitHub Pages to build master and then switched back to gh-pages and that seemed to resolve the issue. Note that the master branch build for the commit that did not trigger Pages has previously failed. In both cases, the failed deployment followed a master commit whose workflow previously failed and now passed. Not sure if this has any relevance.

**Comment by dhimmel** [comment] 2020-02-18 20:55
> I had to kind of "confirm" to Github in the settings of the repository that I really wanted to deploy that web site from the gh-pages branch.

Yeah, I think this is the case for me too. Initially upon going to the settings:

> ![image](https://user-images.githubusercontent.com/1117703/74776832-4b330c80-5266-11ea-80de-b2560f590326.png)

And then after re-selecting "gh-pages" branch for source:

> ![image](https://user-images.githubusercontent.com/1117703/74776900-76b5f700-5266-11ea-9698-a231e0a0595f.png)

Subsequently, I make a dummy commit like `git commit --allow-empty --message "rebuild"`.

**Comment by nicolas-van** [comment] 2020-02-19 09:48
Yeah, I had exactly the same behavior in the Settings page.

Another problem I had additionally was that adding a empty commit after fixing the settings didn't seemed sufficient. It triggered the Gihub Actions workflow but not the Github Pages workflow. It seemed necessary to really alter the content of the `gh-pages` branch in order to publish. It may be useful that say that I'm using Parcel, which generates exactly the same content byte-per-byte given the same source files to optimize caches, and that I use a `.nojekyll` file to avoid problems.

I think Github has some mechanism to avoid publishing if the `gh-pages` didn't changed, at least when using the `.nojekyll` file.

By the way, this is completely unrelated but it could be a good idea to add that `.nojekyll` file by default in your action. 99% of the users will need it, will probably not read the whole documentation so they won't know, and will inevitably encounter a hard to debug problem sooner or later. (I'm convinced all serious users of Github Pages already lost at least one hour of their time because of that damn file like I did ^^ )

**Comment by dhimmel** [comment] 2020-02-19 14:30
> Another problem I had additionally was that adding a empty commit after fixing the settings didn't seemed sufficient

If using an empty commit with this action, you would have to set `allow_empty_commit: true` in the YAML. Could that have been the issue?

**Comment by slonopotamus** [comment] 2020-02-19 21:26
I've read this thread three times, but couldn't quite understand - does deployment work with `GITHUB_TOKEN` at the end or not? README now states that it ~doesn't~ does, but this issue is still open.

**Comment by peaceiris** [comment] 2020-02-19 22:35
@slonopotamus Yes, the deployment with `GITHUB_TOKEN` has worked well on public repositories since a week ago. But, we have no official announcement by GitHub. I opened #115 to update the README. Maybe, we need more time to check whether `GITHUB_TOKEN` is stable, or not, before merging that pr.

**Closed** 2020-02-24 10:35 UTC
Labels: enhancement

**Comment by peaceiris** [comment] 2020-02-24 10:40
Finally, I put the `github_token` as a first example on the README.  🎉  #115 

If the deployment with `GITHUB_TOKEN` in public repositories fails again, we can reopen this issue.

Thanks!
