### ISSUE TITLE
proposal: Upgrade dependency to node16

### ISSUE THREAD

**Issue by isobel-cullen** [peaceiris/actions-gh-pages#786] opened 2022-10-13 14:02 UTC
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

The action should be updated to run on Node16 as Github now shows a warning for actions running on Node12, see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### Describe the solution you'd like

Update the action to run on Node16

**Comment by peaceiris** [comment] 2022-10-13 14:06
Thanks, duplicate of https://github.com/peaceiris/actions-gh-pages/issues/677

**Comment by isobel-cullen** [comment] 2022-10-13 14:33
Sorry, I didn't see that one. Feel free to close this one.

**Closed** 2022-10-13 14:39 UTC
Labels: duplicate, proposal

**Comment by peaceiris** [comment] 2022-10-23 15:01
https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.9.0
