### ISSUE TITLE
keep_files creates subdir instead of overwriting contents of same-name dir

### ISSUE THREAD

**Issue by quite** [peaceiris/actions-gh-pages#509] opened 2020-10-10 06:54 UTC
I'm using this action here, with `keep_files: true` (currently set to `false`) https://github.com/fruktkartan/fruktkartan/blob/master/.github/workflows/deploy-production.yml#L24

I'm quite confident that the latest `v3` deploys `js/file` to `js/js/file`, when the `js` directory already exists (same for `fonts` etc).

**Comment by quite** [comment] 2020-10-10 06:55
I'm setting `keep_files: false` for now.

**Comment by peaceiris** [comment] 2020-10-10 23:44
Thanks.

Duplicate of #507 and related to #324

**Comment by peaceiris** [comment] 2020-10-11 01:37
@hathawayj @quite

Could you test the branch `fix-copy-assets` as follows?

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@fix-copy-assets
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    keep_files: true
```

**Comment by hathawayj** [comment] 2020-10-12 15:57
I modified my main.yml action with the above settings and then pushed a new markdown file for projects and everything seem to build correctly.  Thanks for the fix.

**Comment by peaceiris** [comment] 2020-10-14 09:31
[Release actions-github-pages v3.7.1 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.7.1)

Thank you!

**Closed by peaceiris** 2020-10-14 09:31 UTC
Labels: bug
