### ISSUE TITLE
Action failed with 403

### ISSUE THREAD

**Issue by jrappen** [peaceiris/actions-gh-pages#322] opened 2020-05-22 19:06 UTC
上田さん、どうもお早う御座います、

I have the following issue with your action:

## Affected repository

<https://github.com/da-michele/da-michele.com>

## Affected action

<https://github.com/da-michele/da-michele.com/blob/master/.github/workflows/continuous-deployment.yml>

## Commit causing the issue

<https://github.com/da-michele/da-michele.com/commit/b1a436a2bb85b1a7f4cd363ddb07b2d60abede12>

## Screenshot

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/8577450/82699647-52a2f100-9c6d-11ea-8c9a-b65e1b1973c9.png">

## Things I have checked

* I (@jrappen) as well as a friend (@Vinci2020) are organization owners of <https://github.com/da-michele>
  * I (@jrappen) as well as a friend (@Vinci2020) are in the <https://github.com/da-michele/teams/dev> team, which has admin rights for that repo
* third party actions are allowed for that organization
  * third party actions are allowed for that repo
* this is a public repo, unaffected by billing rules
  * the billing page in the organization settings doesn't have anything that should cause this error

---

If you have any input, on how to resolve this, I'd appreciate it.

**Comment by jrappen** [comment] 2020-05-22 19:08
Duplicate of #319

---

Maybe?

**Comment by jrappen** [comment] 2020-05-22 19:12
https://www.githubstatus.com/ looks bad at the moment.

**Comment by peaceiris** [comment] 2020-05-22 19:17
おはようございます 😄  (early morning 4 a.m. I was waked up by many CI errors.)

Yes this seems to be a duplicate of #319

Try to deploy again when GitHub starts to work well.

**Closed** 2020-05-22 19:48 UTC
Labels: support
