### ISSUE TITLE
Give an option to not omit .github dir

### ISSUE THREAD

**Issue by diauweb** [peaceiris/actions-gh-pages#415] opened 2020-07-25 10:54 UTC
### Is your feature request related to a problem? Please describe
I am using this Action to update files in my master branch, including a workflow file (which is to schedule a trigger to another workflow). 

But as [Here](https://github.com/peaceiris/actions-gh-pages/blob/main/src/git-utils.ts#L20) filters, this Action ignores the .github dir, which prevents the workflow file to be created

### Describe the solution you'd like
An option to force copy .github (and .git?) directory

**Comment by peaceiris** [comment] 2020-07-25 10:59
Duplicate of #163. Please watch the issue.

**Closed by peaceiris** 2020-07-25 10:59 UTC
Labels: proposal
